/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apache_pdfbox_ocr_tesseract_TessBaseAPI */

#ifndef _Included_com_apache_pdfbox_ocr_tesseract_TessBaseAPI
#define _Included_com_apache_pdfbox_ocr_tesseract_TessBaseAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apache_pdfbox_ocr_tesseract_TessBaseAPI
 * Method:    nativeClassInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_apache_pdfbox_ocr_tesseract_TessBaseAPI_nativeClassInit
  (JNIEnv *, jclass);

/*
 * Class:     com_apache_pdfbox_ocr_tesseract_TessBaseAPI
 * Method:    nativeConstruct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_apache_pdfbox_ocr_tesseract_TessBaseAPI_nativeConstruct
  (JNIEnv *, jobject);

/*
 * Class:     com_apache_pdfbox_ocr_tesseract_TessBaseAPI
 * Method:    nativeFinalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_apache_pdfbox_ocr_tesseract_TessBaseAPI_nativeFinalize
  (JNIEnv *, jobject);

/*
 * Class:     com_apache_pdfbox_ocr_tesseract_TessBaseAPI
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_apache_pdfbox_ocr_tesseract_TessBaseAPI_nativeInit
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_apache_pdfbox_ocr_tesseract_TessBaseAPI
 * Method:    nativeClear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_apache_pdfbox_ocr_tesseract_TessBaseAPI_nativeClear
  (JNIEnv *, jobject);

/*
 * Class:     com_apache_pdfbox_ocr_tesseract_TessBaseAPI
 * Method:    nativeEnd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_apache_pdfbox_ocr_tesseract_TessBaseAPI_nativeEnd
  (JNIEnv *, jobject);

/*
 * Class:     com_apache_pdfbox_ocr_tesseract_TessBaseAPI
 * Method:    nativeSetImageBytes
 * Signature: ([BIIII)V
 */
JNIEXPORT void JNICALL Java_com_apache_pdfbox_ocr_tesseract_TessBaseAPI_nativeSetImageBytes
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_apache_pdfbox_ocr_tesseract_TessBaseAPI
 * Method:    nativeSetImagePix
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_apache_pdfbox_ocr_tesseract_TessBaseAPI_nativeSetImagePix
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_apache_pdfbox_ocr_tesseract_TessBaseAPI
 * Method:    nativeSetRectangle
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_apache_pdfbox_ocr_tesseract_TessBaseAPI_nativeSetRectangle
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_apache_pdfbox_ocr_tesseract_TessBaseAPI
 * Method:    nativeGetUTF8Text
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_apache_pdfbox_ocr_tesseract_TessBaseAPI_nativeGetUTF8Text
  (JNIEnv *, jobject);

/*
 * Class:     com_apache_pdfbox_ocr_tesseract_TessBaseAPI
 * Method:    nativeGetRegions
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_apache_pdfbox_ocr_tesseract_TessBaseAPI_nativeGetRegions
  (JNIEnv *, jobject);

/*
 * Class:     com_apache_pdfbox_ocr_tesseract_TessBaseAPI
 * Method:    nativeGetWords
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_apache_pdfbox_ocr_tesseract_TessBaseAPI_nativeGetWords
  (JNIEnv *, jobject);

/*
 * Class:     com_apache_pdfbox_ocr_tesseract_TessBaseAPI
 * Method:    nativeMeanConfidence
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_apache_pdfbox_ocr_tesseract_TessBaseAPI_nativeMeanConfidence
  (JNIEnv *, jobject);

/*
 * Class:     com_apache_pdfbox_ocr_tesseract_TessBaseAPI
 * Method:    nativeWordConfidences
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_apache_pdfbox_ocr_tesseract_TessBaseAPI_nativeWordConfidences
  (JNIEnv *, jobject);

/*
 * Class:     com_apache_pdfbox_ocr_tesseract_TessBaseAPI
 * Method:    nativeSetVariable
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_apache_pdfbox_ocr_tesseract_TessBaseAPI_nativeSetVariable
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_apache_pdfbox_ocr_tesseract_TessBaseAPI
 * Method:    nativeSetDebug
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_apache_pdfbox_ocr_tesseract_TessBaseAPI_nativeSetDebug
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_apache_pdfbox_ocr_tesseract_TessBaseAPI
 * Method:    nativeSetPageSegMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_apache_pdfbox_ocr_tesseract_TessBaseAPI_nativeSetPageSegMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_apache_pdfbox_ocr_tesseract_TessBaseAPI
 * Method:    nativeGetResultIterator
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_apache_pdfbox_ocr_tesseract_TessBaseAPI_nativeGetResultIterator
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
